<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'DATABASE_URL' => 'postgresql://evwrit:evwrit@127.0.0.1:5432/evwrit?serverVersion=12&charset=utf8',
  'DB_CONNECTION' => 'pgsql',
  'DB_HOST' => '127.0.0.1',
  'DB_PORT' => '5432',
  'DB_DATABASE' => 'evwrit',
  'DB_USERNAME' => 'evwrit',
  'DB_PASSWORD' => 'evwrit',
);
