name: evwrit

services:

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./var/postgres/data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  
  elasticsearch:
    build: 
      context: .
      dockerfile: elasticsearch.Dockerfile
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      http.port: 9200
      transport.host: localhost
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      ELASTIC_PASSWORD: "elastic"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./var/elasticsearch/data:/var/lib/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
      ssh: 
        - default
    env_file:
      - .env.prod
    ports:
      - "8080:80"
    depends_on:
      - postgresql
      - elasticsearch

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - pgadmin.env
    depends_on:
      - postgresql

