# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    elastic_search_client:
        class: App\Service\ElasticSearch\Client
        arguments: ['%elasticsearch.config%']
        public: true
    App\Service\ElasticSearch\Client: '@elastic_search_client'

    text_basic_search_service:
        class: App\Service\ElasticSearch\Search\TextBasicSearchService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%', '%elasticsearch.debug%']
        public: true
    App\Service\ElasticSearch\Search\TextBasicSearchService: '@text_basic_search_service'

    text_materiality_search_service:
        class: App\Service\ElasticSearch\Search\TextMaterialitySearchService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%', '%elasticsearch.debug%']
        public: true
    App\Service\ElasticSearch\Search\TextMaterialitySearchService: '@text_materiality_search_service'

    linguistic_annotation_search_service:
        class: App\Service\ElasticSearch\Search\LexicogrammerAnnotationSearchService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%', '%elasticsearch.debug%']
        public: true
    App\Service\ElasticSearch\Search\LexicogrammerAnnotationSearchService: '@linguistic_annotation_search_service'

    language_annotation_search_service:
        class: App\Service\ElasticSearch\Search\LanguageAnnotationSearchService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%', '%elasticsearch.debug%']
        public: true
    App\Service\ElasticSearch\Search\LanguageAnnotationSearchService: '@language_annotation_search_service'

    orthotypo_annotation_search_service:
        class: App\Service\ElasticSearch\Search\OrthoTypoAnnotationSearchService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%', '%elasticsearch.debug%']
        public: true
    App\Service\ElasticSearch\Search\OrthoTypoAnnotationSearchService: '@orthotypo_annotation_search_service'

    text_structure_search_service:
        class: App\Service\ElasticSearch\Search\TextStructureSearchService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%', '%elasticsearch.debug%']
        public: true
    App\Service\ElasticSearch\Search\TextStructureSearchService: '@text_structure_search_service'

    text_index_service:
        class: App\Service\ElasticSearch\Index\TextIndexService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%']
        public: true
    App\Service\ElasticSearch\Index\TextIndexService: '@text_index_service'

    level_index_service:
        class: App\Service\ElasticSearch\Index\LevelIndexService
        arguments: ['@elastic_search_client','%elasticsearch.index_prefix%']
        public: true
    App\Service\ElasticSearch\Index\LevelIndexService: '@level_index_service'


    text_repository:
        class: App\Repository\TextRepository
        arguments: []
        public: true
    App\Repository\TextRepository: '@text_repository'

    language_annotation_repository:
        class: App\Repository\LanguageAnnotationRepository
        arguments: []
        public: true
    App\Repository\LanguageAnnotationRepository: '@language_annotation_repository'

    orthotypo_annotation_repository:
        class: App\Repository\TypographyAnnotationRepository
        arguments: []
        public: true
    App\Repository\TypographyAnnotationRepository: '@orthotypo_annotation_repository'