declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}

declare module '*.pug' {
  const content: any
  export default content
}

// Webpack inline loader URLs (e.g. generated by vue-loader for componentNormalizer)
declare module '!*' {
  const content: any
  export default content
}
